build:
    environment:
        node: '9'
    cache:
        directories:
            - node_modules/
    dependencies:
        before:
            - npm install
    tests:
        before:
            - vendor/bin/phpunit --coverage-clover=laravel-test-examples-coverage
        override:
            -
                command: 'npm test coverage-test'
                coverage:
                    file: 'coverage/clover.xml'
                    format: 'clover'
